name: Update latest blog posts
on:
  schedule:
    - cron: '0 0 * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://abashev.com/atom.xml"
